
---

# Basic provisioning example
- name: Launching AWS ec-2 instances
  hosts: localhost
  connection: local
  tasks:
  - name: launch AWS instance using Ansible
    ec2:
      aws_access_key: AKIA6DFCP2MHRFYSIZAU
      aws_secret_key: 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
      key_name: Frankfurt-keys-AWS
      instance_type: t2.micro
      image: ami-05f7491af5eef733a
      region: eu-central-1
      wait: yes
      group: Main-ec2
      count: 1
      vpc_subnet_id: subnet-fe63ebb2
      assign_public_ip: yes
    register: ec2

  - name: EIP
    ec2_eip:
            aws_access_key: AKIA6DFCP2MHRFYSIZAU
            aws_secret_key: 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
            in_vpc: yes
            state: present
            device_id: "{{ ec2.instances[0].id }}"
            region: eu-central-1
            ip: 3.68.250.21
    register: instance_eip
